[package]
name = "lunnar-cal"
version = "0.1.0"
edition = "2024"

[dependencies]
chinese-lunisolar-calendar = { version = "0.2.1", features = ["ba-zi-weight"] }
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.30.0"
time = { version = "0.3.45", features = ["formatting", "parsing"] }
time-macros = { version = "0.2.25", features = ["parsing", "formatting"] }
